// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js__Int = require("rescript-js/src/Js__Int.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var lines = Fs.readFileSync("src/assets/day1-report.txt", "ascii").split("\n").map(function (l) {
      return Belt_Option.getWithDefault(Js__Int.fromString(l), 0);
    });

function countPreviousIncreases(arr) {
  return arr.map(function (value, index) {
                var previous = arr[index - 1 | 0];
                if (previous !== undefined) {
                  return {
                          previous: previous,
                          increased: value > previous
                        };
                } else {
                  return {
                          previous: undefined,
                          increased: false
                        };
                }
              }).reduce((function (sum, result) {
                if (result.increased) {
                  return sum + 1 | 0;
                } else {
                  return sum;
                }
              }), 0);
}

var total = countPreviousIncreases(lines);

var Part1 = {
  total: total
};

var total$1 = countPreviousIncreases(lines.slice(2).map(function (_value, index) {
          return lines.slice(index, index + 3 | 0).reduce((function (total, value) {
                        return total + value | 0;
                      }), 0);
        }));

var Part2 = {
  total: total$1
};

console.log("Part 1: ", total);

console.log("Part 2: ", total$1);

exports.lines = lines;
exports.countPreviousIncreases = countPreviousIncreases;
exports.Part1 = Part1;
exports.Part2 = Part2;
/* lines Not a pure module */
